<?php
/**
 * Template Part for displaying a single Resource Tool card.
 *
 * This file is intended to be used inside the WordPress Loop, likely for the 'resource_tools' CPT.
 *
 * @package HappyPortfolio
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

// -----------------------------------------------------
// 1. DATA RETRIEVAL
// -----------------------------------------------------

$post_id    = get_the_ID();
$link       = get_post_meta($post_id, '_wedo_tool_link', true);
$title_attr = the_title_attribute(['echo' => false]);

// Get the featured image ID for responsive output
$thumbnail_id = get_post_thumbnail_id($post_id);

// -----------------------------------------------------
// 2. HTML OUTPUT
// -----------------------------------------------------

if ($link) :
    ?>
    <a class="group rounded-lg flex flex-col justify-start items-start p-3 bg-white border border-[#e6e6e6] relative row-gap-4 transition-all duration-75 ease-in overflow-hidden hover:bg-hoverBg"
       href="<?php echo esc_url($link); ?>"
       title="<?php echo esc_attr($title_attr); ?>"
       target="_blank"
       rel="noopener noreferrer">

        <?php if ($thumbnail_id) :
            // 💡 PERFORMANCE IMPROVEMENT: Using wp_get_attachment_image()
            // Using 'thumbnail' size is appropriate for a small 32x32px element.
            echo wp_get_attachment_image(
                $thumbnail_id,
                'thumbnail', // Standard small size (e.g., 150x150)
                false,
                [
                    'class'   => 'w-8 h-8 object-cover rounded-md mb-2', // Custom Tailwind classes for sizing
                    'loading' => 'lazy',
                    'alt'     => $title_attr,
                ]
            );
        endif; ?>

        <h3 class="text-sm! mb-1! font-medium!">
            <?php the_title(); ?>
            <span class="opacity-0 text-xs! group-hover:opacity-100 transition-opacity duration-300">↗</span>
        </h3>
        <p class="text-xs! text-gray11! mb-1.5">
            <?php
            // Use get_the_excerpt() directly, as it's already generated by WordPress.
            echo trim(get_the_excerpt());
            ?>
        </p>
    </a>
<?php endif; ?>
